[package]
name = "graph"
version = "0.2.0"
authors = ["Mitchell Bruckner <mbruckner807@gmail.com>"]

[dependencies]
starfield-render = { git = "https://github.com/mabruckner/starfield-render.git", rev = "31df22a" }

